#%RAML 1.0
title: EA Bank customer account Creation API
description:  This API is used to create a new customer account with EA Bank
protocols:
  - HTTPS
  - HTTP
version: v1

securitySchemes: 
  secure: !include /Schemas/securityScheme.raml
securedBy:
  - secure
/createAccount:
  post:
    queryParameters:
      customerName:
        required : true
        maxLength: 45
        minLength: 4
      bank:
        required: true
        enum:
          - EABank
          - ICICI 
          - AXIS 
          - HDFC
      accaount_type:
        required: true
        enum:
          - savings
          - current
      branchName:
        required: true
        minLength: 4
        maxLength: 10
    body:
      application/json:
        type: !include /DataType/EABankDataType.raml
        examples: !include /Examples/request/InputRequestExample.raml
    responses:
      201:
        body:
          application/json:
            example: !include /Examples/responce/ResponceExample.raml
              
            